### PR TITLE
Added a blog post about making duckdb extension

### PR DESCRIPTION
**Pull request by grammaright**
I added a blog post for creating a DuckDB extension.
The blog post describes making a table function; using this we can fetch data from outside DuckDB.

### CODE REVIEW

**Comment by adriens** [comment]
Very cool, I really wanted to implement pipeline like table functions.
Did you implement in cpp or other ?

**Comment by grammaright** [comment]
@adriens 
I used C++. I'm not sure another language can be used directly.

**Comment by adriens** [comment]
Yup @grammaright , months ago I asked if it may possible to implement them with go, rust as they are more popular, attractive, hence could make people contribute more.

Some related discussions : 

- [Feature Request: UDF support for C API ](https://github.com/duckdb/duckdb/discussions/4874)
- [Feature Request: Adding more UDFs to duckdb](https://github.com/duckdb/duckdb/discussions/6031)
- [How to create a new extension](https://github.com/duckdb/duckdb/discussions/2493)

**Comment by grammaright** [comment]
@adriens 
Oh, I see. It will be really useful if they support it. 
I should follow up. Thanks for sharing!

**Review by davidgasquez — APPROVED** [review]
Thanks Kyoseung!

**Pull request merged**
