### PR TITLE
:books:  Add duckdb datasets on Kaggle

### PR DESCRIPTION
**Pull request by adriens**
# :grey_question: About

`duckdb` is an awesome way to to build and strore data... and **[Kaggle](https://www.kaggle.com/) awesome to share it so people can build things on top of it.**

# :moneybag: Benefits of this section

- :heavy_check_mark: Make it possible to people to discover `duckdb` features from a browser
- :heavy_check_mark: Discover usecases
- :heavy_check_mark: Have fun with useful data
- :heavy_check_mark: Produce knowledge (ML, dataviz, ...) on top of `duckdb`

### CODE REVIEW

**Comment by davidgasquez** [comment]
Heya @adriens! I agree it would be great to add at least the current [`endoflife-date-database`] DuckDB dataset to this repository. That said, the current PR doesn't follow the [Awesome Guidelines](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md). Specifically, it shouldn't have any extrea bullet points besides the dataset one.

What do you think of adding the following line under **Projects Powered by DuckDB**?

```
- [`endoflife.date` database](https://www.kaggle.com/datasets/adriensales/endoflife-date-database)
```

**Review by adriens — COMMENTED** [review]
Hey @davidgasquez , here we go :smile_cat:

**Review by davidgasquez — APPROVED** [review]
Awesome! Thanks a lot! :raised_hands:

**Comment by adriens** [comment]
> Awesome! Thanks a lot! 🙌

Thanks a lot for the good vibes around :duck: :pray:

**Comment by adriens** [comment]
:loudspeaker: https://www.kaggle.com/datasets/adriensales/endoflife-date-database/discussion/476568

**Comment by davidgasquez** [comment]
Congratz on the dataset! Very well curated and documented. Have you thought about uploading it to HuggingFace Datasets? That's another great platform to host datasets.

**Comment by adriens** [comment]
> Congratz on the dataset! Very well curated and documented. Have you thought about uploading it to HuggingFace Datasets? That's another great platform to host datasets.

:star_struck: Absolutely @davidgasquez  but prior to that I want to make a blog post on how to auomate that. I just have to shoot the video as the "for dummies" note book is ready :smile_cat:

**Pull request merged**
