### PR TITLE
Add GitHub CI action to run linkchecker

### PR DESCRIPTION
**Pull request by szarnyasg**
This currently fails; PR #5 contains the fix for the link.

### CODE REVIEW

**Comment by davidgasquez** [comment]
Nice! This is something I've been wanting to add. Do we need to keep the `report.html` file commited to the repo or could it be ignored?

**Comment by szarnyasg** [comment]
Hi @davidgasquez! The `report.html` file doesn't get committed to the repository, instead its content is piped to the `GITHUB_STEP_SUMMARY` environment variable. GitHub Actions picks up this variable and shows it on the "Summary" page of the action's run:
https://github.com/davidgasquez/awesome-duckdb/actions/runs/5609014374

**Comment by davidgasquez** [comment]
> The report.html file doesn't get committed to the repository, instead its content is piped to the GITHUB_STEP_SUMMARY environment variable. 

Nice! I think it might have been commited though: https://github.com/davidgasquez/awesome-duckdb/pull/6/files#diff-bcb3d7751facd01f1f8b72deeca5da4c5d10f3ece35d89abd11e2ec14ef91760.

It's ok! Let's merge this and clean later. :sweat_smile:

**Comment by szarnyasg** [comment]
Ah, I see now. The fix is incoming!

**Pull request merged**
