### PR TITLE
:crab: doc(Client APIs) : Add Crate duckdb

### PR DESCRIPTION
**Pull request by adriens**
Add https://docs.rs/duckdb/latest/duckdb/, 

> "duckdb-rs is an ergonomic wrapper for using DuckDB from Rust. It attempts to expose an interface similar to [rusqlite](https://github.com/rusqlite/rusqlite)."

### CODE REVIEW

**Comment by adriens** [comment]
I got inspired by:
- https://github.com/davidgasquez/awesome-duckdb/pull/71

**Review by davidgasquez — COMMENTED** [review]
Hey @adriens! 

Is'nt `duckdb-rs` already in the list?

https://github.com/davidgasquez/awesome-duckdb/blob/512497c3a16c771524bf3dee69381f29a4bce1f0/README.md?plain=1#L53

**Comment by adriens** [comment]
It's indeed pointing to https://github.com/duckdb/duckdb-rs : shouldn't we point to this last one ?

**Comment by davidgasquez** [comment]
Great question! To be honest I don't have any strong opinions there. The current one (DuckDB website) looks a great option for me. Any reason to go straight to the GitHub repository?

**Comment by adriens** [comment]
>  Any reason to go straight to the GitHub repository?

To stay-up-to-date with base code, issues and releases :thinking:

**Comment by davidgasquez** [comment]
Fair enough! Mind updating the PR with the original bullet point updated to the GitHub repository? Happy to do it too. 

Thanks for bearing with me @adriens!

**Comment by adriens** [comment]
> Thanks for bearing with me @adriens!

Thanks for the nive and positive feedbacks @davidgasquez :pray:

**Comment by adriens** [comment]
> Happy to do it too.

I have activated common edition on the PR : what do you think of modifiying so we both contributed to this one ?

**Comment by davidgasquez** [comment]
Done! :heavy_check_mark:

**Comment by adriens** [comment]
:raised_hands:

**Pull request merged**
